language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - sudo apt-get install -yqq cups cups-pdf
  - composer self-update || true
  - composer update
  - composer --prefer-source --dev update

script: ./vendor/bin/atoum -d tests/ -ncc
